// Code generated by automatic for 'github.com/rs/xid'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlibs

import (
	"github.com/rs/xid"
	"reflect"
)

func init() {
	Symbols["github.com/rs/xid"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrInvalidID": reflect.ValueOf(&xid.ErrInvalidID).Elem(),
		"FromBytes":    reflect.ValueOf(xid.FromBytes),
		"FromString":   reflect.ValueOf(xid.FromString),
		"New":          reflect.ValueOf(xid.New),
		"NewWithTime":  reflect.ValueOf(xid.NewWithTime),
		"NilID":        reflect.ValueOf(xid.NilID),
		"Sort":         reflect.ValueOf(xid.Sort),

		// type definitions
		"ID": reflect.ValueOf((*xid.ID)(nil)),
	}
}
