// Code generated by automatic for 'gopkg.in/mgo.v2'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlibs

import (
	mgov2 "gopkg.in/mgo.v2"
	"reflect"
)

func init() {
	Symbols["gopkg.in/mgo.v2"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":               reflect.ValueOf(mgov2.Dial),
		"DialWithInfo":       reflect.ValueOf(mgov2.DialWithInfo),
		"DialWithTimeout":    reflect.ValueOf(mgov2.DialWithTimeout),
		"ErrCursor":          reflect.ValueOf(&mgov2.ErrCursor).Elem(),
		"ErrNotFound":        reflect.ValueOf(&mgov2.ErrNotFound).Elem(),
		"Eventual":           reflect.ValueOf(mgov2.Eventual),
		"GetStats":           reflect.ValueOf(mgov2.GetStats),
		"IsDup":              reflect.ValueOf(mgov2.IsDup),
		"Monotonic":          reflect.ValueOf(mgov2.Monotonic),
		"Nearest":            reflect.ValueOf(mgov2.Nearest),
		"ParseURL":           reflect.ValueOf(mgov2.ParseURL),
		"Primary":            reflect.ValueOf(mgov2.Primary),
		"PrimaryPreferred":   reflect.ValueOf(mgov2.PrimaryPreferred),
		"ResetStats":         reflect.ValueOf(mgov2.ResetStats),
		"RoleClusterAdmin":   reflect.ValueOf(mgov2.RoleClusterAdmin),
		"RoleDBAdmin":        reflect.ValueOf(mgov2.RoleDBAdmin),
		"RoleDBAdminAny":     reflect.ValueOf(mgov2.RoleDBAdminAny),
		"RoleRead":           reflect.ValueOf(mgov2.RoleRead),
		"RoleReadAny":        reflect.ValueOf(mgov2.RoleReadAny),
		"RoleReadWrite":      reflect.ValueOf(mgov2.RoleReadWrite),
		"RoleReadWriteAny":   reflect.ValueOf(mgov2.RoleReadWriteAny),
		"RoleRoot":           reflect.ValueOf(mgov2.RoleRoot),
		"RoleUserAdmin":      reflect.ValueOf(mgov2.RoleUserAdmin),
		"RoleUserAdminAny":   reflect.ValueOf(mgov2.RoleUserAdminAny),
		"Secondary":          reflect.ValueOf(mgov2.Secondary),
		"SecondaryPreferred": reflect.ValueOf(mgov2.SecondaryPreferred),
		"SetDebug":           reflect.ValueOf(mgov2.SetDebug),
		"SetLogger":          reflect.ValueOf(mgov2.SetLogger),
		"SetStats":           reflect.ValueOf(mgov2.SetStats),
		"Strong":             reflect.ValueOf(mgov2.Strong),

		// type definitions
		"BuildInfo":      reflect.ValueOf((*mgov2.BuildInfo)(nil)),
		"Bulk":           reflect.ValueOf((*mgov2.Bulk)(nil)),
		"BulkError":      reflect.ValueOf((*mgov2.BulkError)(nil)),
		"BulkErrorCase":  reflect.ValueOf((*mgov2.BulkErrorCase)(nil)),
		"BulkResult":     reflect.ValueOf((*mgov2.BulkResult)(nil)),
		"Change":         reflect.ValueOf((*mgov2.Change)(nil)),
		"ChangeInfo":     reflect.ValueOf((*mgov2.ChangeInfo)(nil)),
		"Collation":      reflect.ValueOf((*mgov2.Collation)(nil)),
		"Collection":     reflect.ValueOf((*mgov2.Collection)(nil)),
		"CollectionInfo": reflect.ValueOf((*mgov2.CollectionInfo)(nil)),
		"Credential":     reflect.ValueOf((*mgov2.Credential)(nil)),
		"DBRef":          reflect.ValueOf((*mgov2.DBRef)(nil)),
		"Database":       reflect.ValueOf((*mgov2.Database)(nil)),
		"DialInfo":       reflect.ValueOf((*mgov2.DialInfo)(nil)),
		"GridFS":         reflect.ValueOf((*mgov2.GridFS)(nil)),
		"GridFile":       reflect.ValueOf((*mgov2.GridFile)(nil)),
		"Index":          reflect.ValueOf((*mgov2.Index)(nil)),
		"Iter":           reflect.ValueOf((*mgov2.Iter)(nil)),
		"LastError":      reflect.ValueOf((*mgov2.LastError)(nil)),
		"MapReduce":      reflect.ValueOf((*mgov2.MapReduce)(nil)),
		"MapReduceInfo":  reflect.ValueOf((*mgov2.MapReduceInfo)(nil)),
		"MapReduceTime":  reflect.ValueOf((*mgov2.MapReduceTime)(nil)),
		"Mode":           reflect.ValueOf((*mgov2.Mode)(nil)),
		"Pipe":           reflect.ValueOf((*mgov2.Pipe)(nil)),
		"Query":          reflect.ValueOf((*mgov2.Query)(nil)),
		"QueryError":     reflect.ValueOf((*mgov2.QueryError)(nil)),
		"Role":           reflect.ValueOf((*mgov2.Role)(nil)),
		"Safe":           reflect.ValueOf((*mgov2.Safe)(nil)),
		"ServerAddr":     reflect.ValueOf((*mgov2.ServerAddr)(nil)),
		"Session":        reflect.ValueOf((*mgov2.Session)(nil)),
		"Stats":          reflect.ValueOf((*mgov2.Stats)(nil)),
		"User":           reflect.ValueOf((*mgov2.User)(nil)),
	}
}
