// Code generated by automatic for 'github.com/TianQinS/fastapi/post'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlibs

import (
	"github.com/TianQinS/fastapi/post"
	"reflect"
)

func init() {
	Symbols["github.com/TianQinS/fastapi/post"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ASYNC_JOB_QUEUE_MAXLEN": reflect.ValueOf(post.ASYNC_JOB_QUEUE_MAXLEN),
		"Close":                  reflect.ValueOf(post.Close),
		"GPost":                  reflect.ValueOf(&post.GPost).Elem(),
		"ITEM_QUEUE_CAPACITY":    reflect.ValueOf(post.ITEM_QUEUE_CAPACITY),
		"JobWorkers":             reflect.ValueOf(&post.JobWorkers).Elem(),
		"JobWorkersLock":         reflect.ValueOf(&post.JobWorkersLock).Elem(),
		"MAX_SLEEP_TIME":         reflect.ValueOf(post.MAX_SLEEP_TIME),
		"NewPost":                reflect.ValueOf(post.NewPost),
		"ORI_ROUTINE_NUM":        reflect.ValueOf(post.ORI_ROUTINE_NUM),

		// type definitions
		"JobWorker": reflect.ValueOf((*post.JobWorker)(nil)),
		"Post":      reflect.ValueOf((*post.Post)(nil)),
		"QueueMsg":  reflect.ValueOf((*post.QueueMsg)(nil)),
		"RpcObject": reflect.ValueOf((*post.RpcObject)(nil)),
	}
}
