// Code generated by automatic for 'github.com/tidwall/rtree/base'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlibs

import (
	"github.com/tidwall/rtree/base"
	"reflect"
)

func init() {
	Symbols["github.com/tidwall/rtree/base"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(base.New),

		// type definitions
		"RTree": reflect.ValueOf((*base.RTree)(nil)),
	}
}
