// Code generated by automatic for 'github.com/TianQinS/websocket/database'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlibs

import (
	"github.com/TianQinS/websocket/database"
	"reflect"
)

func init() {
	Symbols["github.com/TianQinS/websocket/database"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Close":                  reflect.ValueOf(database.Close),
		"CreateIndex":            reflect.ValueOf(database.CreateIndex),
		"DB":                     reflect.ValueOf(&database.DB).Elem(),
		"Delete":                 reflect.ValueOf(database.Delete),
		"GPost":                  reflect.ValueOf(&database.GPost).Elem(),
		"Get":                    reflect.ValueOf(database.Get),
		"GetValue":               reflect.ValueOf(database.GetValue),
		"Initialize":             reflect.ValueOf(database.Initialize),
		"MDB_JOB_KEY":            reflect.ValueOf(database.MDB_JOB_KEY),
		"NewMongoDB":             reflect.ValueOf(database.NewMongoDB),
		"NewRdb":                 reflect.ValueOf(database.NewRdb),
		"NewRedisClientByConfig": reflect.ValueOf(database.NewRedisClientByConfig),
		"NewRedisClientCluster":  reflect.ValueOf(database.NewRedisClientCluster),
		"NewRedisClientSentinel": reflect.ValueOf(database.NewRedisClientSentinel),
		"NewRedisClientSimple":   reflect.ValueOf(database.NewRedisClientSimple),
		"Put":                    reflect.ValueOf(database.Put),
		"PutExpire":              reflect.ValueOf(database.PutExpire),
		"RedisMust":              reflect.ValueOf(database.RedisMust),

		// type definitions
		"MDB": reflect.ValueOf((*database.MDB)(nil)),
		"Rdb": reflect.ValueOf((*database.Rdb)(nil)),
	}
}
