// Code generated by automatic. DO NOT EDIT.
package stdlibs

import (
	"reflect"

	"github.com/containous/yaegi/stdlib"
)

// Symbols variable stores the map of stdlib symbols per package
var Symbols = map[string]map[string]reflect.Value{}

func init() {
	for mod, val := range stdlib.Symbols {
		Symbols[mod] = val
	}
}	
